/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ji' at '16-12-13 下午5:05' with Gradle 3.2.1
 *
 * @author ji, @date 16-12-13 下午5:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
